feat：EOL管理ダッシュボードと製品詳細ページの追加 (#1052)
* feat：EOL管理ダッシュボードと製品詳細ページの追加

- サポート対象製品のEOL情報を表示するためのProductEolListPageとProductEolDetailPageを実装しました。
- サービスの依存関係とそのEOLステータスを管理するためのServiceEolDashboardを作成しました。
- テストと開発を容易にするために、サポート対象製品とサービスのモックデータを追加しました。
- ユーザーエクスペリエンスを向上させるため、Material-UIコンポーネントを使用してUIを強化しました。
- 製品リストとサービスリストの両方にフィルタリングと検索機能を追加しました。
- 様々な状態とデータシナリオを紹介するために、ServiceEolDashboardにStorybookストーリーを追加しました。

* delete Vulnerability

* update openapi

* add eol api

* delete unused api

* add eol menu

* fix getEoLs request type

* change EoL icon

* fix getEoLs request type

* fix tcApi

* add EoLProductCategoryList

* Topic/product eo l page (#1059)

* Split files by component

* fix ProductEolPage

* fix latestUpdate

* fix EoL Link

* fix search target

* fix unmatch category label

* Add @ts-expect-error TS7016 to suppress missing type definition error

* topic/ServiceEolDashboardPage (#1060)

* topic/ServiceEolDashboardPage

* commoditize

* delete safe

* commoditize

* fix format

* commoditize getDiffDays

* fix getEolStatus

* fix getStatus

* fix getDiffText

* fix WARNING_THRESHOLD_DAYS

* fix getDiffDays

---------

Co-authored-by: Yuki Murasawa <148930319+yuki-murasawa@users.noreply.github.com>
Co-authored-by: TsurutaYoshiki <yoshiki.tsrututa.ak@hitachi-solutions.com>
Co-authored-by: Shikou <shiko.dejima.uw@hitachi-solutions.com>
Co-authored-by: dejima-shikou <165614333+dejima-shikou@users.noreply.github.com>
Co-authored-by: TsurutaYoshiki <142189177+TsurutaYoshiki@users.noreply.github.com>